# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_hello_world',
                'doc_host': 'https://swartchris8.github.io',
                'git_url': 'https://github.com/swartchris8/nbdev_hello_world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': { 'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py'),
                                        'nbdev_hello_world.core.say_hello': ('core.html#say_hello', 'nbdev_hello_world/core.py')}}}
